name: Trigger my downstream workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ping parent repo
        run: |
          curl -X POST https://api.github.com/repos/paulf-999/dbt_demo_vertical_proj_struct/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.GIT_CREDENTIALS }} \
          --data '{"ref": "main" }'