name: Trigger my downstream workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ping parent repo
        run: |
          curl -X POST https://api.github.com/repos/paulf-999/dbt_demo_vertical_proj_struct/.github/workflows/demo_call_parent.yml/dispatches \
          -H 'Accept:application/vnd.github' \
          -u ${{ secrets.GIT_CREDENTIALS }} \
          --data '{"ref": "main" }'