name: Trigger my downstream workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
        curl -X POST https://api.github.com/repos/paulf-999/dbt_demo_vertical_proj_struct/dispatches \
        -H 'Accept:application/vnd.github' \
        -u ${{ secrets.GIT_CREDENTIALS }} \
        --data '{"ref": "main" }'